### ISSUE TITLE
Tests - basic testing via Nette\Tester

### ISSUE THREAD

**Issue by f3l1x** [Markette/Gopay#24]

**Comment by haltuf** [comment]
I have some tests in here - https://github.com/haltuf/Gopay
Would it be sufficient?

**Comment by f3l1x** [comment]
@haltuf It looks great.

Could you..?

* [ ] Split tests and Travis CI
* [ ] Squash all tests commits to one
* [ ] Squash all CI commits to one
* [ ] Add newline to end of files
* [ ] Send PR 1 - tests
* [ ] Send PR 2 - CI

**Comment by haltuf** [comment]
Sure, I will. Sorry for being dumb, but can you explain/link some info about "Add newline to end of files"?
Does it mean just adding new empty line to every file, or does it mean something more profound?

**Comment by f3l1x** [comment]
Yes, adding new empty line. Sorry for typo.

**Comment by haltuf** [comment]
I created two branches as requested, but the thing is, unless issue #17 is solved, the tests will fail now (I solved the issue for me, but the solution isn't very good and I would hesitate to commit it)
Do you want me to send PRs anyway or shall we wait until issue #17 is solved?

**Comment by f3l1x** [comment]
@haltuf Thanks. Could you run tests with this branch? https://github.com/f3l1x/Gopay/commits/patch-17 You have to set channels via extensions 

```neon
	channels:
		gopay: Gopay - Elektronická peněženka
```

Or manually via `$service->addChannel($service::METHOD_CARD_UNICREDITB, 'Gopay - Elektronická peněženka')`

**Comment by haltuf** [comment]
If you manage to merge your changes with haltuf@3cc7297, then now the tests are passing.
