### ISSUE TITLE
Implement new API functions

### ISSUE THREAD

**Issue by haltuf** [Markette/Gopay#35]
I believe implementing other features from the official API should be a long-term milestone:

 - preauthorized payments, capture preauthorization, void preauthorization
 - recurrent payments, perform reccurence, void reccurence
 - refunds
 - partial refunds

**Comment by f3l1x** [comment]
Do you want to implement something of the list?

**Comment by haltuf** [comment]
I might need to implement recurrent payments in the upcoming weeks, so I could take it as an opportunity to add this functionality to this extension. But no promises yet.

**Comment by haltuf** [comment]
![gopay](https://cloud.githubusercontent.com/assets/325759/7458137/5cc6df28-f292-11e4-9338-f203b6a634fe.png)

@f3l1x I drew the types of payment with the respective actions, that should be possible to do with them.

Couple of thoughts:
 - I think creating the RedirectResponse should be seperated from Service::pay() function as an independent public function, e.g. `createResponse($paymentsession_id)`. It already came handy for me couple of times in the past and now it would be needed even more.
 - I'm not sure about the concept of `ReturnedPayment` in the context of upcoming changes, but didn't manage to find a better solution yet. Same goes for static singleton.
 - the originator of the methods or "actions" in red colour need not be the object itself (especially in cases like isFraud, isPaid). E.g. some "manager" should use the injected gopay-api for communication via Soap, instead of static calls or static singleton methods.

What do you think?

**Comment by f3l1x** [comment]
I like an idea. :+1: 

Current **Service** is a god object. 

We could:
- split Buttons to BindingService
- split paying, restoring, refunding to PaymentService
- ReturnedPayment does not have to be lazyloading, why that.. It could ask whether isPaymentDone immediately (it remove getStatus), we could move **isFraud** to PaymentService, and, voala, ugly static holder is gone.

I'm now thinking about separating some **Configuration** (gopayId, gopaySecretKey, mode, successUrl, failureUrl, channels, lang). What do you think?

And also separate constants to some **ChannelTypes** or something. 

Nice sketch btw. It's some tool or just manual?

**Comment by haltuf** [comment]
I never used this extension with Nette Forms, so I can't comment the first point, as I lack any experience with this. The rest sounds great.

Regarding the **Configuration** it would be great, unless such a change makes it harder for users to use this extension (i.e. not requiring to create such Configuration object manually to be able to use Markette/Gopay)

Separating constants sounds great for me, too.

Thank you, the sketch was done manually, using the Wacom graphic tablet (not to be confused with normal tablet, it's a completely different gadget) :-)

**Comment by f3l1x** [comment]
@haltuf Implemented in new v3.0.0.

https://github.com/Markette/Gopay/releases/tag/v3.0.0-alpha

Thank you for idea. :smiley:
