### ISSUE TITLE
PHP 5.4

### ISSUE THREAD

**Issue by f3l1x** [Markette/Gopay#37]
* Short array syntax
* Traits (maybe)

**Comment by f3l1x** [comment]
@hranicka @vojtech-dobes @haltuf Are you ok with it?

**Comment by haltuf** [comment]
I lean to be conservative in adopting new features, when it does not have any practical meaning.
Short array syntax is rather cosmetical change, which IMHO only raises requirements (from PHP 5.3 to 5.4)
Traits - I can't say, never used them before. I have some awareness, but no practical experience :-)

**Comment by hrach** [comment]
The reasons should not be practical, but political - 5.3 is insecure and dangerous. Drop it!

**Comment by haltuf** [comment]
Ok, I had no idea that it is so serious...

**Comment by hrach** [comment]
Well, we are fighting for better world, don't we? :)

**Comment by hranicka** [comment]
@hrach :smile

In my opinion 5.3 compatibility is not necessary. Also 5.4 has been released 3 years ago and should be installed on almost hosts.

**Comment by f3l1x** [comment]
I suggest migrate to min 5.4 or even 5.5. For the future.

**Comment by vojtech-dobes** [comment]
Regarding people with old PHP: good library can be incentive to upgrade :). I would raise the minimum PHP to 5.4 for now. And then raised it to 5.5 exactly when 5.4's "Security fixes only" phase will end. Which is [until 14 Sep 2015](http://php.net/supported-versions.php).

**Comment by hrach** [comment]
@vojtech-dobes :+1:

**Comment by hranicka** [comment]
@vojtech-dobes :thumbsup:

**Comment by f3l1x** [comment]
@vojtech-dobes 5.3 will be in "Security fixes only" in 3 months. Don't be better raise it to 5.5 at once?

**Comment by f3l1x** [comment]
Implemented.
