### ISSUE TITLE
Platební karty

### ISSUE THREAD

**Issue by martinsifra** [Markette/Gopay#46]
Pokouším se o provedení platby pomocí platební karty, ale ani pokud předvyberu metodu (Service::METHOD_CARD_GPB) ani pokud nevyberu nic, GoPay mi nenabídne platbu kartou. V administraci ji mám samozřejmě povolenou. Používám "dev-master".

**Comment by martinsifra** [comment]
Zjistil jsem, že nikde v administraci nemám karty "A" ani "B". Ve všech pouze "Platební karty GP WebPay C".

**Comment by f3l1x** [comment]
Muzes mi ukazat nastaveni v `configu` a take jak tu platbu volas? Diky.

**Comment by martinsifra** [comment]
```
gopay:
	gopayId: 8460513952
	gopaySecretKey: naQ6H5eUMaFKyWyPLpwVNChc
	testMode: true
	channels:
		eu_om: yes
		gopay: yes
		card_ceskas: yes
		card_unicreditb: yes
		supercash: yes
		premiumsms: yes
		mplatba: yes
		komercnib: yes
		raiffeisenb: yes
		mbank: yes
		fiob: yes
		unicreditb: yes
		slovenskas: yes
		transfer: yes
```
```
$response = $this->gopay->pay($payment, Service::METHOD_CARD_GPB, function ($paymentId) {…});
```

**Comment by martinsifra** [comment]
Teď jsem mluvil s člověkem s GoPay. Je to jak jsem psal. Platební karty jsou podle poskytovatele typů A, B a C. Musel mi tam cosi nastavit, abych mohl používat B, protože na všech účtech máme aktivní pouze C. Zkoušel jsem hledat v jejich dokumentaci, jaký řetězec (kód platby) pro to C posílat, ale nikde jsem nic nenašel…

**Comment by f3l1x** [comment]
@martinsifra Co z toho plyne? Povolili ti to a tedka uz to funguje?

**Comment by martinsifra** [comment]
Jop funguje, ale ještě zjistím, jestli je potřeba pro to C dodělat nový kód nebo je to pouze na jejich nastavení.

**Comment by martinsifra** [comment]
Tak je to na nich, kterou verzi platební karty nastaví. Zavírám.
