### ISSUE TITLE
Zrušenie recurrent platby

### ISSUE THREAD

**Issue by MaRmARk0** [Markette/Gopay#53]
Zaimplementoval som opakujúce sa platby pomocou markette/gopay@3.0.0 na Nette ^2.3.0, ale neviem ako zrušiť existujúci RecurrentPayment na strane GoPay. 

`RecurrentPaymentService::restorePayment()` vráti objekt `ReturnedPayment`, ktory má rôzne metódy (`isPaid, isFraud, isWaiting...`) a buď priamo v tomto objekte, alebo v samotnom `RecurrentPaymentService` by som čakal metódu napr. `cancelRecurrentPayment()`

[Gopay Docs > Zrušení platby](https://doc.gopay.com/cs/#zrušení-opakování-platby)

**Comment by f3l1x** [comment]
@MaRmARk0 

Diky za upozorneni, zkusim doimplementovat ruseni opakovanych a predautorizovanych plateb.

**Comment by MaRmARk0** [comment]
@f3l1x 
Vďaka za rýchly fix! `cancelRecurrent()` funguje správne aj na strane GoPay, :+1: ale samotná metóda `cancelRecurrent()` nevracia žiadnu hodnotu (vždy vráti `NULL`). Asi by bolo fajn, keby vrátila aspoň boolean. :)

**Comment by f3l1x** [comment]
@MaRmARk0 

Muzu tam vracet `return TRUE`, protoze ani oficialni GoPay API nic nevraci. 

https://github.com/Markette/GopayApi/blob/master/src/GopaySoap.php#L852-L910

Takhle se to bud provede nebo se vyhodi vyjimka. Stejne by jsi ji mel nejspis odchytavat.

**Comment by MaRmARk0** [comment]
Výnimky si odchytávam, ale z nejakého dôvodu mi to nikdy nehodilo CALL_RESULT_ACCEPTED výnimku a tak som netušil že čo sa deje...či to prešlo, neprešlo, alebo čo.

Mňa len v prvej chvíli ma napadlo niečo takéto. Možno by to bolo handy.

    public function cancelRecurrent($paymentSessionId)
    {
        try {
            $this->gopay->soap->voidRecurrentPayment(
                $paymentSessionId,
                $this->gopay->config->getGopayId(),
                $this->gopay->config->getGopaySecretKey()
            );
        } catch (Exception $e) {
			if ($e->getMessage() !== GopayHelper::CALL_RESULT_ACCEPTED) {
				throw new GopayException($e->getMessage(), 0, $e);
			}
			
			return TRUE;
        }
    }`

**Comment by f3l1x** [comment]
Uff no, uplne se mi to nelibi. :-)

To return true by se melo vracet pokazde kdyz se nevyhodi vyjimka, takze mimo try/catch block nejspis. Ale rikam si k cemu mi to bude.

Kdybych to pouzival, tak bych mel nejspis takovyhle zapis.

```php
try{ 
    $service->cancelRecurrent($paymentSessionId);
    $this->processSuccessCanceling();
} catch (GopayException $e) {
    $this->processInvalidCanceling();
}
```

Tzn, ze return true vubec nevyuziju. Urcite si muzes podedit `RecurrentPaymentService` a obalit si to do vlastni. 

Slo by to?

**Comment by MaRmARk0** [comment]
Lol, vôbec ma nenapadlo si `RecurrentPaymentService` podediť. :)) 
Tak okej teda, takto to ako to je to bude hádam stačiť.
Vďaka!

**Comment by f3l1x** [comment]
Neni zac. :-)

Melo by to jit takto.

```yaml
extensions: 
    gopay: Markette\Gopay\DI\Extension

services:
    gopay.service.payment: MyPaymentService
    gopay.service.recurrentPayment: MyRecurrentPaymentService
    gopay.service.preAuthorizedPayment: MyPreAuthorizedPaymentService
```

Pokud by jsi to chtel vyuzivat jako do ted. :-)

**Comment by MaRmARk0** [comment]
U mně dobrý. :) Môžeme to podľa mňa zatvoriť.

**Comment by f3l1x** [comment]
@MaRmARk0 Diky moc za pomoc. :-)
