### ISSUE TITLE
EET support

### ISSUE THREAD

**Issue by haltuf** [Markette/Gopay#58]
Implement EET support (variant B) according to https://help.gopay.com/cs/tema/propojeni-do-eet/jak-bude-fungovat-napojeni-gopay-do-eet#zakladni

**Comment by f3l1x** [comment]
It looks good. Unfortunately this library use old SOAP Gopay gateway. What about to add this to https://github.com/Markette/GopayInline. What do you think?

**Comment by f3l1x** [comment]
@haltuf What do you think? Could we closed this and implement int in GopayInline?

https://github.com/Markette/GopayInline/issues/19

**Comment by haltuf** [comment]
It's up to you, I guess. Currently, I'm using this version of Gopay implementation. If it's neccessary to switch to GopayInline, I'll have to deal with it :-)

**Comment by f3l1x** [comment]
@haltuf Well, I would like to step-by-step discontinue of developing of this library and move all resources to the new replacement GopayInline. It's modern and it uses JSON REST API.

So, can you switch to new version? I hope it will be not hard to adopt it.

**Comment by haltuf** [comment]
It's subject to client's approval, but I support moving to modern version.

**Comment by f3l1x** [comment]
@haltuf Keep me in touch please. I keep it open for now. Thank you.

**Comment by haltuf** [comment]
@f3l1x Client approved, we will switch to GopayInline and REST API.
