### ISSUE TITLE
https://testgw.gopay.cz ssl certificate expired

### ISSUE THREAD

**Issue by hantc** [Markette/Gopay#60]
Hi,

gopay few months ago switched testing server to new url: https://gw.sandbox.gopay.com/

https://testgw.gopay.cz/ is no longer valid.

More info below:

> Dobrý den,
> 
> URL adresa testovacího prostředí ve formátu "https://testgw.gopay.cz/..." přestala být funkční
> 
> počínaje minulým týdnem, kdy na evedené doméně vypršela životnost SSL certifikátu.
> 
> Veřejně již prezentujeme dokumentaci pouze k aktuální verzi platební brány pomocí REST API
> 
> a to na webu https://doc.gopay.com/cs/. Tato dokumentace je dostupná od roku 2015.
> 
> Děkujeme.

**Comment by f3l1x** [comment]
Hi. Thanks. Would you mind to prepare PR for this change please?

**Comment by hantc** [comment]
I'll try to, it would be my first github PR ever, so be tolerant, please :)

**Comment by hantc** [comment]
I found out, it's a change in another repo - my MR is here:
https://github.com/Markette/GopayApi/pull/8

But as I can see, there is a guy who solved it 3 days ago:
https://github.com/Markette/GopayApi/pull/7

**Comment by f3l1x** [comment]
Could you please test it with gopay-api with latest changes?

**Comment by hantc** [comment]
Honestly, I'm not able to download it via composer. Even specific commit:

`"markette/gopay": "dev-master#69fa440a4c9ce95844bf86a18d94a7191ca5152c",`

error:

`
- Installing ←[32mmarkette/gopay←[39m (←[33mdev-master 69fa440←[39m): Cloning 69fa440a4c
    ←[30;43m69fa440a4c9ce95844bf86a18d94a7191ca5152c is gone (history was rewritten?)←[39;49m
    ←[30;43mFailed to download markette/gopay from source: Failed to execute git checkout "69fa440a4c9ce95844bf86a18d94a7191ca5152c" -- && g
it reset --hard "69fa440a4c9ce95844bf86a18d94a7191ca5152c" --

fatal: reference is not a tree: 69fa440a4c9ce95844bf86a18d94a7191ca5152c
←[39;49m
    ←[30;43mNow trying to download from dist←[39;49m
  - Installing ←[32mmarkette/gopay←[39m (←[33mdev-master 69fa440←[39m): DownloadinDownloadinDownloading (←[37;41mfailed←[39;49m)
←[37;41m
       ←[39;49m
←[37;41m  [Composer\Downloader\TransportException]
       ←[39;49m
←[37;41m  The "https://api.github.com/repos/Markette/Gopay/zipball/69fa440a4c9ce95844bf86a18d94a7191ca5152c" file could not be downloaded (H
TTP/1  ←[39;49m
←[37;41m  .1 302 Found)
`

Any ideas?

**Comment by f3l1x** [comment]
You've been trying to download `markette/gopay`, but the change was in `markette/gopay-api`. ;-) Keep your `markette/gopay` as it and append `markette/gopay-api` with commit reference.

**Comment by zvitek** [comment]
Hello, can I ask how to resolve this problem?
I have `markette/gopay` in version ^3.1 and I would like to update `markette/gopay-api` on fix commit with this pudates: https://github.com/Markette/GopayApi/commit/69fa440a4c9ce95844bf86a18d94a7191ca5152c

`"markette/gopay-api": "dev-master#69fa440a4c9ce95844bf86a18d94a7191ca5152c"`

But composer has problem with dependecies and I don't know hot to resolve it.

Thx for help

**Comment by f3l1x** [comment]
Well, it seems commit with change is in master and not in 2.5.x branch.

Could you try in the meanwhile this please? I'll try to backport it to 2.5.x.

```
    "require": {
        "markette/gopay": "^3.1",
        "markette/gopay-api": "3.0.0 as 2.5.3"
    }
```

**Comment by f3l1x** [comment]
@hantc @zvitek It's also in 2.5.x branch.

https://github.com/Markette/GopayApi/commit/2d5f2381b05083ce7a1b5873ddc0adece718c2c3

You should change it to `gopay-api: 2.5.x-dev` or specify commit.

**Comment by zvitek** [comment]
@f3l1x It works very well! Thx for fast resolve!

**Comment by f3l1x** [comment]
I think we can close it. Thank you guys.  @zvitek @hantc
