### ISSUE TITLE
Remove Nette\Object

### ISSUE THREAD

**Issue by f3l1x** [Markette/Gopay#67]

**Comment by ondrakub** [comment]
@f3l1x Hi, is there a chance that it will be fixed soon? Or can I prepare PR?
I need this library to run on PHP 7.2

**Comment by f3l1x** [comment]
Hi, could you please prepare PR? It would be great. If there's no need to use Nette\Object don't replace it but remove it.

**Comment by ondrakub** [comment]
I've removed it #69

**Comment by f3l1x** [comment]
Resolved, thanks.

**Comment by f3l1x** [comment]
Bumped in v3.2.0
