### ISSUE TITLE
Bitcoin platby

### ISSUE THREAD

**Issue by Lexinek** [Markette/Gopay#68]
Ahoj, rád bych se zeptal, jak udělat platbu přes bitcoin :-). Chybí konstanta `GoPay::METHOD_BITCOIN`. Tak jestli bude stačit tam přidat nějaký string? [V dokumentaci](https://doc.gopay.com/cs/#payment_instrument) je uveden string `BITCOIN`, ale nejsem si jist, jestli ta dokumentace odpovídá balíčku, ostatní typy plateb tomu také neodpovídají.

Ještě bude asi potřeba přidat do configu podporu pro channels bitcoinu
```neon
gopay:
    payments:
        channels:
            bitcoin: yes
```

Jde mi o to, co dát ve volání `PaymentService::pay($payment, $channel, $callback)` do `$channel`.

**Comment by f3l1x** [comment]
Idealne mrkni na Markette/GopayInline balicek a tam posli PR prosim. :-)

**Comment by Lexinek** [comment]
Přiznám se, že s `Markette/GopayInline` jsem ještě nepracoval a v projektu je použito právě `Markette/Gopay`. 

Zkusím kouknout na docku a snad bude přechod jednoduchý :-) PR pošlu.

**Comment by f3l1x** [comment]
Diky moc, Markette/Gopay je SOAP a Markette/GopayInline je nova JSON/REST brana.

**Comment by Lexinek** [comment]
@f3l1x tak u GopayInline už podpora pro BitCoin byla, takže stačilo "jen" přepsat implementaci 😄
